(require 'init-modify-emacs-defaults)
(require 'init-auto-save)
(require 'init-cursor-moving)
(require 'init-buffer-and-window-switching)
(require 'init-helm)
(require 'init-auto-completion)
(require 'init-undo-and-redo)
(require 'init-self-defined-functions)
(require 'init-emacs-server)

(provide 'init-startup)
