(use-package init-modify-emacs-defaults)
(use-package init-auto-save)
(use-package init-cursor-moving)
(use-package init-buffer-and-window-switching)
(use-package init-ivy)
(use-package init-auto-completion)
(use-package init-undo-and-redo)
(use-package init-self-defined-functions
  :bind (("C-^" . wenshan-join-line-from-next-line)
         ("s-:" . wenshan-switch-to-minibuffer-window)
         ("s-g" . wenshan-delete-current-file)
         ("<backtab>" . wenshan-toggle-fold-based-on-indentation)
         )
  )
(use-package init-emacs-server)

(provide 'init-startup)
