(use-package init-modify-emacs-defaults)
(use-package init-auto-save)
(use-package init-cursor-moving)
(use-package init-buffer-and-window-switching)
(use-package init-ivy)
(use-package init-auto-completion)
(use-package init-undo-and-redo)
(use-package init-self-defined-functions
  :bind (("C-^" . wenshan-join-line-from-next-line)
         ("s-:" . wenshan-switch-to-minibuffer-window)
         ("s-g" . wenshan-delete-current-file)
         ("<backtab>" . wenshan-toggle-fold-based-on-indentation)
         ("s-b" . wenshan-previous-blank-line)
         ("s-n" . wenshan-next-blank-line)
         ("C-x C-o" . wenshan-open-file-at-cursor)
         ("C-6" . wenshan-select-block)
         ("C-7" . wenshan-select-line)
         ("C-8" . wenshan-select-sentence)
         ("C-9" . wenshan-select-text-in-quote)
         )
  )
(use-package init-emacs-server)

(provide 'init-startup)
